server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking-route
          uri: lb://booking-service
          predicates: 
           - Path=/booking/**
          filters:
             - name: CircuitBreaker
               args:
                name: booking-route
                fallbackUri: forward:/booking-fallback   
                
eureka:
   client:
     service-url:
         defaultZone : http://localhost:8761/eureka/
